-- Migration 016: Add AI-generated copy column to landing_pages
-- ai_copy stores JSON: { headline, subheadline, hook, bullets, cta, social_proof }
-- generated by Claude at deploy time based on asset content + campaign brief

ALTER TABLE landing_pages ADD COLUMN ai_copy TEXT DEFAULT NULL;
