-- Migration 020: Replace all campaigns with ones matched to actual CSV data keywords

DELETE FROM campaigns;

-- Campaign 1: Information Technology Leadership
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (1, 1, 'IT Leadership Network', 'active', 500, 5.00, 'IT Infrastructure Strategy Guide', 'https://example.com/assets/it-strategy.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What is your top IT priority?","type":"text"}]', '#1e40af', '#1e3a8a', '#3b82f6', 'https://img.icons8.com/fluency/96/code.png', '["United States"]', '["Technology","Financial Services","Healthcare","Manufacturing"]', '["Information Technology","IT Manager","IT Director","IT Operations","IT Security"]', '["201-500","501-1000","1001-5000","5000+"]', 'Targets any role with IT/Information Technology in title');

-- Campaign 2: Chief Officers (CIO, CFO, CISO, CTO)
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (2, 1, 'C-Suite Officer Network', 'active', 300, 10.00, 'Chief Officer Strategy Guide', 'https://example.com/assets/c-officer.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What is your top strategic priority?","type":"text"}]', '#dc2626', '#991b1b', '#ef4444', 'https://img.icons8.com/fluency/96/businessman.png', '["United States"]', '["Technology","Financial Services","Healthcare","Manufacturing","Fortune 500"]', '["Chief Information Officer","Chief Financial Officer","Chief Technology Officer","Chief Information Security Officer","CIO","CFO","CISO","CTO","Chief "]', '["501-1000","1001-5000","5000+"]', 'Targets Chief-level officers (CIO, CFO, CISO, CTO)');

-- Campaign 3: Director-Level Positions
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (3, 1, 'Director Leadership Summit', 'active', 600, 4.50, 'Director's Strategic Playbook', 'https://example.com/assets/director-playbook.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What operational challenge is top-of-mind?","type":"text"}]', '#7c3aed', '#6d28d9', '#a855f7', 'https://img.icons8.com/fluency/96/crown.png', '["United States"]', '["Technology","Financial Services","Healthcare","Manufacturing","Operations"]', '["Director ","Director,","Director of","Director-","Director|"]', '["201-500","501-1000","1001-5000","5000+"]', 'Targets any Director-level title');

-- Campaign 4: VP & Senior Vice President
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (4, 1, 'VP Executive Network', 'active', 250, 8.00, 'VP Strategy & Execution', 'https://example.com/assets/vp-strategy.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What are your top 3 strategic priorities?","type":"text"}]', '#0f766e', '#134e4a', '#14b8a6', 'https://img.icons8.com/fluency/96/crown.png', '["United States"]', '["Technology","Financial Services","Healthcare","Manufacturing"]', '["VP ","VP|","VP of","Vice President","V.P."]', '["501-1000","1001-5000","5000+"]', 'Targets VP and Senior Vice President roles');

-- Campaign 5: Security & Compliance Leaders
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (5, 1, 'Security & Compliance Forum', 'active', 350, 6.50, 'Security Strategy in 2026', 'https://example.com/assets/security-strategy.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What is your biggest security challenge?","type":"text"}]', '#dc2626', '#7f1d1d', '#ef4444', 'https://img.icons8.com/fluency/96/lock.png', '["United States"]', '["Technology","Financial Services","Healthcare","Insurance"]', '["Security","Cyber","Compliance","Investigations","CISO"]', '["201-500","501-1000","1001-5000","5000+"]', 'Targets security, cyber, and compliance focused roles');

-- Campaign 6: Finance & Accounting Leaders
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (6, 1, 'Finance Leadership Forum', 'active', 400, 5.50, 'Financial Strategy & Planning', 'https://example.com/assets/finance-strategy.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What are your finance priorities?","type":"text"}]', '#b45309', '#78350f', '#f59e0b', 'https://img.icons8.com/fluency/96/money.png', '["United States"]', '["Financial Services","Healthcare","Manufacturing","Retail"]', '["Finance","Financial","Accounting","Accountant","Controller","Treasurer","CFO"]', '["201-500","501-1000","1001-5000","5000+"]', 'Targets finance and accounting leadership');

-- Campaign 7: Operations & Management
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (7, 1, 'Operations Excellence Program', 'active', 450, 5.00, 'Operations Strategy Guide', 'https://example.com/assets/ops-strategy.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What operational challenges exist?","type":"text"}]', '#059669', '#065f46', '#10b981', 'https://img.icons8.com/fluency/96/settings.png', '["United States"]', '["Manufacturing","Healthcare","Retail","Operations"]', '["Operations","Operations Manager","Operations Director","Quality Control Manager","Manager "]', '["201-500","501-1000","1001-5000","5000+"]', 'Targets operations and management roles');

-- Campaign 8: Technology & Engineering
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (8, 1, 'Technology Leader Summit', 'active', 380, 7.00, 'Technology Strategy 2026', 'https://example.com/assets/tech-strategy.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What is your technology roadmap?","type":"text"}]', '#1e40af', '#1e3a8a', '#3b82f6', 'https://img.icons8.com/fluency/96/code.png', '["United States"]', '["Technology","Financial Services","Healthcare","Manufacturing"]', '["Technology","Engineer","Architect","Developer","Applications"]', '["201-500","501-1000","1001-5000","5000+"]', 'Targets technology and engineering roles');

-- Campaign 9: Healthcare & Clinical Leaders
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (9, 1, 'Healthcare Leadership Forum', 'active', 200, 8.50, 'Healthcare Operations Strategy', 'https://example.com/assets/healthcare-strategy.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What healthcare challenge are you facing?","type":"text"}]', '#7c2d12', '#92400e', '#ea580c', 'https://img.icons8.com/fluency/96/medical.png', '["United States"]', '["Healthcare","Hospitals","Pharmaceuticals","Medical Devices"]', '["Nursing","Medical","Clinical","Health","Hospital"]', '["201-500","501-1000","1001-5000","5000+"]', 'Targets healthcare and clinical leaders');

-- Campaign 10: Senior Manager & Manager Network
INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (10, 1, 'Manager Excellence Program', 'active', 550, 4.00, 'Manager Success Guide', 'https://example.com/assets/manager-guide.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What is your biggest team challenge?","type":"text"}]', '#6366f1', '#4f46e5', '#818cf8', 'https://img.icons8.com/fluency/96/supervisor.png', '["United States"]', '["Technology","Financial Services","Healthcare","Manufacturing"]', '["Manager ","Manager,","Senior Manager","Program Manager","Sr. Manager"]', '["201-500","501-1000","1001-5000","5000+"]', 'Targets all Manager-level titles');
