-- Clear existing campaigns and their leads (avoid FK constraint issues)
DELETE FROM campaign_leads WHERE campaign_id IN (SELECT id FROM campaigns);
DELETE FROM campaigns WHERE client_id = 1;

-- ═══════════════════════════════════════════════════════════════════════
-- 5 COMPLETED CAMPAIGNS (for user testing)
-- ═══════════════════════════════════════════════════════════════════════

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (1, 1, 'CFO Roundtable 2026', 'completed', 200, 12.00, 'CFO Priorities Report', 'https://example.com/assets/cfo-report.pdf', '2025-10-01', '2026-03-31', '["LinkedIn"]', '[]', '[{"question":"What is your 2026 financial strategy?","type":"text"}]', '#0f766e', '#134e4a', '#14b8a6', 'https://img.icons8.com/fluency/96/money.png', '["United States"]', '["Financial Services","Healthcare","Technology"]', '["CFO","Chief Financial Officer"]', '["501-1000","1001-5000","5000+"]', 'Completed: CFO and finance executive targeting');

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (2, 1, 'IT Director Forum', 'completed', 150, 9.50, 'IT Strategy Whitepaper', 'https://example.com/assets/it-strategy.pdf', '2025-11-01', '2026-03-31', '["Apollo"]', '[]', '[{"question":"What is your IT modernization priority?","type":"text"}]', '#1e40af', '#1e3a8a', '#3b82f6', 'https://img.icons8.com/fluency/96/code.png', '["United States"]', '["Technology","Financial Services"]', '["Director of IT","IT Director","Director Technology"]', '["201-500","501-1000","1001-5000"]', 'Completed: IT/Technology director targeting');

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (3, 1, 'COO Executive Summit', 'completed', 180, 11.00, 'COO Excellence Guide', 'https://example.com/assets/coo-guide.pdf', '2025-12-01', '2026-03-31', '["LinkedIn"]', '[]', '[{"question":"How do you measure operational success?","type":"text"}]', '#059669', '#065f46', '#10b981', 'https://img.icons8.com/fluency/96/settings.png', '["United States"]', '["Manufacturing","Healthcare","Retail"]', '["COO","Chief Operations Officer","Chief Ops"]', '["201-500","501-1000","1001-5000","5000+"]', 'Completed: COO and operations executive targeting');

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (4, 1, 'VP Sales Leadership', 'completed', 220, 8.75, 'Sales Excellence Framework', 'https://example.com/assets/sales-framework.pdf', '2025-10-15', '2026-03-31', '["Apollo"]', '[]', '[{"question":"What are your revenue challenges?","type":"text"}]', '#dc2626', '#7f1d1d', '#ef4444', 'https://img.icons8.com/fluency/96/growing-chart.png', '["United States"]', '["Technology","Financial Services","Retail"]', '["VP of Sales","VP Sales","Vice President Sales"]', '["501-1000","1001-5000","5000+"]', 'Completed: VP Sales targeting');

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (5, 1, 'CISO Security Forum', 'completed', 120, 15.00, 'Security Leadership Report', 'https://example.com/assets/ciso-report.pdf', '2025-11-15', '2026-03-31', '["LinkedIn"]', '[]', '[{"question":"What is your biggest security threat?","type":"text"}]', '#7c2d12', '#92400e', '#ea580c', 'https://img.icons8.com/fluency/96/lock.png', '["United States"]', '["Financial Services","Healthcare","Technology"]', '["CISO","Chief Information Security Officer","Chief Security"]', '["201-500","501-1000","1001-5000","5000+"]', 'Completed: CISO and security executive targeting');

-- ═══════════════════════════════════════════════════════════════════════
-- 5 DRAFT/REQUEST CAMPAIGNS (waiting to be deployed)
-- ═══════════════════════════════════════════════════════════════════════

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (6, 1, 'CMO Brand Summit', 'draft', 250, 10.50, 'Brand Strategy 2026', 'https://example.com/assets/brand-strategy.pdf', '2026-04-01', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What is your brand challenge?","type":"text"}]', '#8b5cf6', '#6d28d9', '#a855f7', 'https://img.icons8.com/fluency/96/marketing.png', '["United States"]', '["Technology","Retail","Consumer Goods"]', '["CMO","Chief Marketing Officer","Chief Brand"]', '["201-500","501-1000","1001-5000","5000+"]', 'Draft: CMO and marketing executive targeting');

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (7, 1, 'HR Director Network', 'draft', 180, 7.25, 'HR Strategy Playbook', 'https://example.com/assets/hr-strategy.pdf', '2026-04-15', '2026-12-31', '["LinkedIn"]', '[]', '[{"question":"What is your talent challenge?","type":"text"}]', '#7c3aed', '#6d28d9', '#a855f7', 'https://img.icons8.com/fluency/96/people.png', '["United States"]', '["Technology","Financial Services","Healthcare","Manufacturing"]', '["Director of HR","HR Director","Human Resources Director"]', '["201-500","501-1000","1001-5000"]', 'Draft: HR/People director targeting');

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (8, 1, 'Chief Legal Officer Forum', 'draft', 140, 14.00, 'Legal Strategy Report', 'https://example.com/assets/legal-strategy.pdf', '2026-05-01', '2026-12-31', '["Apollo"]', '[]', '[{"question":"What is your compliance priority?","type":"text"}]', '#2563eb', '#1e40af', '#3b82f6', 'https://img.icons8.com/fluency/96/law.png', '["United States"]', '["Financial Services","Healthcare","Technology"]', '["Chief Legal Officer","CLO","General Counsel"]', '["501-1000","1001-5000","5000+"]', 'Draft: CLO and legal executive targeting');

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (9, 1, 'Chief Product Officer Summit', 'draft', 200, 11.50, 'Product Strategy Framework', 'https://example.com/assets/product-strategy.pdf', '2026-04-20', '2026-12-31', '["LinkedIn","Apollo"]', '[]', '[{"question":"What is your product vision?","type":"text"}]', '#0891b2', '#164e63', '#06b6d4', 'https://img.icons8.com/fluency/96/package.png', '["United States"]', '["Technology","Healthcare","Financial Services"]', '["Chief Product Officer","CPO","Head of Product"]', '["201-500","501-1000","1001-5000","5000+"]', 'Draft: CPO and product executive targeting');

INSERT INTO campaigns (id, client_id, name, status, target, cpl, asset_name, asset_url, start_date, end_date, tal, suppression_list, custom_questions, brand_color, brand_color_secondary, brand_accent, logo_url, geo, industries, titles, company_sizes, notes)
VALUES (10, 1, 'VP Engineering Forum', 'draft', 210, 9.75, 'Engineering Leadership Guide', 'https://example.com/assets/engineering-guide.pdf', '2026-05-01', '2026-12-31', '["LinkedIn"]', '[]', '[{"question":"What is your technical roadmap?","type":"text"}]', '#4f46e5', '#4338ca', '#818cf8', 'https://img.icons8.com/fluency/96/hardware.png', '["United States"]', '["Technology","Financial Services"]', '["VP of Engineering","VP Engineering","Engineering Director","Chief Technology Officer"]', '["501-1000","1001-5000","5000+"]', 'Draft: VP/Chief Engineering targeting');
